services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: sell_car
    environment:
      POSTGRES_USER: joaor
      POSTGRES_PASSWORD: sapulho
      POSTGRES_DB: sell_car_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
